### ISSUE TITLE
How do you compile RigidChips?

### ISSUE THREAD

**Issue by StiffBoards** [siruhu/RC15B27C#1]
It would be nice to have instructions on how to build RigidChips. Open RigidChips(ORC) has instructions, but last time I checked they did not work.

**Comment by ray45422** [comment]
Clone the repository and switch to the `main` branch. Open this repository in Visual Studio 2019 and build. You will probably get an error about the Windows SDK and platform toolset. Install the required components or change them to installed components. In my case, the Windows SDK is change to latest version and the platform toolset is change to "Visual Studio 2019 (v142)".

Open RigidChips may require an additional library called "legacy_stdio_definitions.lib".

**Comment by StiffBoards** [comment]
I got it to build successfully with Visual Studio 2019. First I had to install the package v141_xp though. Thanks for the help!
