### ISSUE TITLE
_RANGE does not function properly when used on the CORE chip

### ISSUE THREAD

**Issue by StiffBoards** [siruhu/RC15B27C#2]
When _RANGE is called on the CORE chip, it returns the distance to terrain behind the CORE chip. It would be useful for _RANGE on the CORE chip to return distance forward, to make it possible to obtain distance to the point the center of the camera on the CORE chip is pointing as.

Should be fairly simple to add another condition specific to CORE chip to luaGetRange in luaSub.cpp.

**Comment by ray45422** [comment]
Current default-branch is [main](https://github.com/siruhu/RC15B27C/tree/main) but not changed yet on GitHub.
This feature already implemented on main branch.

You can get the distance to any direction on the CORE by specifying the vector after the chip number like `_RANGE (chip, lx, ly, lz)`.
When other kind of chip, _RANGE returns the distance to terrain behind the chip.
https://github.com/siruhu/RC15B27C/blob/7747ed3963f487a300929e030454fbe1be8927de/Release/%E3%82%8C%E3%81%82%E3%81%A9%E3%82%81.txt#L35

**Comment by StiffBoards** [comment]
Thanks, I wasn't aware of this!
